# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MMSMagPy.ui'
#
# Created: Thu Jul 21 16:40:05 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MMSMagPy(object):
    def setupUi(self, MMSMagPy):
        MMSMagPy.setObjectName(_fromUtf8("MMSMagPy"))
        MMSMagPy.resize(1122, 793)
        self.centralwidget = QtGui.QWidget(MMSMagPy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.fileStatsGB = QtGui.QGroupBox(self.centralwidget)
        self.fileStatsGB.setGeometry(QtCore.QRect(610, 0, 511, 151))
        self.fileStatsGB.setObjectName(_fromUtf8("fileStatsGB"))
        self.locationTag = QtGui.QWidget(self.fileStatsGB)
        self.locationTag.setGeometry(QtCore.QRect(10, 30, 481, 41))
        self.locationTag.setObjectName(_fromUtf8("locationTag"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.locationTag)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dirLabel = QtGui.QLabel(self.locationTag)
        self.dirLabel.setObjectName(_fromUtf8("dirLabel"))
        self.horizontalLayout.addWidget(self.dirLabel)
        self.timeTag = QtGui.QWidget(self.fileStatsGB)
        self.timeTag.setGeometry(QtCore.QRect(10, 90, 493, 44))
        self.timeTag.setObjectName(_fromUtf8("timeTag"))
        self.gridLayout = QtGui.QGridLayout(self.timeTag)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.statButton = QtGui.QPushButton(self.timeTag)
        self.statButton.setObjectName(_fromUtf8("statButton"))
        self.gridLayout.addWidget(self.statButton, 0, 0, 1, 1)
        self.headerButton = QtGui.QPushButton(self.timeTag)
        self.headerButton.setObjectName(_fromUtf8("headerButton"))
        self.gridLayout.addWidget(self.headerButton, 0, 1, 1, 1)
        self.dataButton = QtGui.QPushButton(self.timeTag)
        self.dataButton.setObjectName(_fromUtf8("dataButton"))
        self.gridLayout.addWidget(self.dataButton, 0, 2, 1, 1)
        self.hodoButton = QtGui.QPushButton(self.timeTag)
        self.hodoButton.setObjectName(_fromUtf8("hodoButton"))
        self.gridLayout.addWidget(self.hodoButton, 0, 3, 1, 1)
        self.focusButton = QtGui.QPushButton(self.timeTag)
        self.focusButton.setObjectName(_fromUtf8("focusButton"))
        self.gridLayout.addWidget(self.focusButton, 0, 4, 1, 1)
        self.plotGB = QtGui.QGroupBox(self.centralwidget)
        self.plotGB.setGeometry(QtCore.QRect(610, 160, 511, 491))
        self.plotGB.setObjectName(_fromUtf8("plotGB"))
        self.dataGB = QtGui.QGroupBox(self.centralwidget)
        self.dataGB.setGeometry(QtCore.QRect(610, 650, 501, 71))
        self.dataGB.setObjectName(_fromUtf8("dataGB"))
        self.editButton = QtGui.QPushButton(self.dataGB)
        self.editButton.setGeometry(QtCore.QRect(20, 30, 110, 32))
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.spectraButton = QtGui.QPushButton(self.dataGB)
        self.spectraButton.setGeometry(QtCore.QRect(150, 30, 110, 32))
        self.spectraButton.setObjectName(_fromUtf8("spectraButton"))
        self.printPanel = QtGui.QPushButton(self.centralwidget)
        self.printPanel.setGeometry(QtCore.QRect(640, 730, 110, 32))
        self.printPanel.setObjectName(_fromUtf8("printPanel"))
        self.plotTabs = QtGui.QTabWidget(self.centralwidget)
        self.plotTabs.setGeometry(QtCore.QRect(0, 0, 610, 800))
        self.plotTabs.setObjectName(_fromUtf8("plotTabs"))
        self.mag = QtGui.QWidget()
        self.mag.setObjectName(_fromUtf8("mag"))
        self.magView = QtGui.QGraphicsView(self.mag)
        self.magView.setGeometry(QtCore.QRect(0, 0, 600, 741))
        self.magView.setLineWidth(-10)
        self.magView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.magView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.magView.setForegroundBrush(brush)
        self.magView.setSceneRect(QtCore.QRectF(0.0, 0.0, 531.0, 707.0))
        self.magView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.magView.setObjectName(_fromUtf8("magView"))
        self.plotTabs.addTab(self.mag, _fromUtf8(""))
        self.processed = QtGui.QWidget()
        self.processed.setObjectName(_fromUtf8("processed"))
        self.processedView = QtGui.QGraphicsView(self.processed)
        self.processedView.setGeometry(QtCore.QRect(0, 0, 600, 741))
        self.processedView.setLineWidth(-10)
        self.processedView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.processedView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.processedView.setForegroundBrush(brush)
        self.processedView.setSceneRect(QtCore.QRectF(0.0, 0.0, 531.0, 707.0))
        self.processedView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.processedView.setObjectName(_fromUtf8("processedView"))
        self.plotTabs.addTab(self.processed, _fromUtf8(""))
        self.BLM = QtGui.QWidget()
        self.BLM.setObjectName(_fromUtf8("BLM"))
        self.BLMView = QtGui.QGraphicsView(self.BLM)
        self.BLMView.setGeometry(QtCore.QRect(0, 0, 600, 741))
        self.BLMView.setLineWidth(-10)
        self.BLMView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BLMView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.BLMView.setForegroundBrush(brush)
        self.BLMView.setSceneRect(QtCore.QRectF(0.0, 0.0, 531.0, 707.0))
        self.BLMView.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.BLMView.setObjectName(_fromUtf8("BLMView"))
        self.plotTabs.addTab(self.BLM, _fromUtf8(""))
        MMSMagPy.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MMSMagPy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuOpen_Set = QtGui.QMenu(self.menuData)
        self.menuOpen_Set.setObjectName(_fromUtf8("menuOpen_Set"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MMSMagPy.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MMSMagPy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MMSMagPy.setStatusBar(self.statusbar)
        self.actionFile = QtGui.QAction(MMSMagPy)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionAbout = QtGui.QAction(MMSMagPy)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPrint = QtGui.QAction(MMSMagPy)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionQuit = QtGui.QAction(MMSMagPy)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionBy_Day = QtGui.QAction(MMSMagPy)
        self.actionBy_Day.setObjectName(_fromUtf8("actionBy_Day"))
        self.actionManually = QtGui.QAction(MMSMagPy)
        self.actionManually.setObjectName(_fromUtf8("actionManually"))
        self.actionFilename = QtGui.QAction(MMSMagPy)
        self.actionFilename.setObjectName(_fromUtf8("actionFilename"))
        self.actionWorking_Directory = QtGui.QAction(MMSMagPy)
        self.actionWorking_Directory.setObjectName(_fromUtf8("actionWorking_Directory"))
        self.menuOpen_Set.addAction(self.actionBy_Day)
        self.menuOpen_Set.addAction(self.actionManually)
        self.menuData.addAction(self.menuOpen_Set.menuAction())
        self.menuData.addAction(self.actionPrint)
        self.menuData.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionWorking_Directory)
        self.menuSettings.addAction(self.actionFilename)
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MMSMagPy)
        self.plotTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MMSMagPy)

    def retranslateUi(self, MMSMagPy):
        MMSMagPy.setWindowTitle(_translate("MMSMagPy", "MMSMagPy", None))
        self.fileStatsGB.setTitle(_translate("MMSMagPy", "File Stats", None))
        self.dirLabel.setText(_translate("MMSMagPy", "directory", None))
        self.statButton.setText(_translate("MMSMagPy", "Data Statistics", None))
        self.headerButton.setText(_translate("MMSMagPy", "Display Header", None))
        self.dataButton.setText(_translate("MMSMagPy", "Display Data", None))
        self.hodoButton.setText(_translate("MMSMagPy", "Hodogram", None))
        self.focusButton.setText(_translate("MMSMagPy", "Focus", None))
        self.plotGB.setTitle(_translate("MMSMagPy", "Plot Controls", None))
        self.dataGB.setTitle(_translate("MMSMagPy", "Data Controls", None))
        self.editButton.setText(_translate("MMSMagPy", "Edit", None))
        self.spectraButton.setText(_translate("MMSMagPy", "Spectral", None))
        self.printPanel.setText(_translate("MMSMagPy", "Print Panel", None))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.mag), _translate("MMSMagPy", "Magnetic Fields GSE", None))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.processed), _translate("MMSMagPy", "Processed", None))
        self.plotTabs.setTabText(self.plotTabs.indexOf(self.BLM), _translate("MMSMagPy", "Magnetic Fields BLM", None))
        self.menuHelp.setTitle(_translate("MMSMagPy", "Help", None))
        self.menuData.setTitle(_translate("MMSMagPy", "Data", None))
        self.menuOpen_Set.setTitle(_translate("MMSMagPy", "Open Set", None))
        self.menuSettings.setTitle(_translate("MMSMagPy", "Settings", None))
        self.actionFile.setText(_translate("MMSMagPy", "file 2", None))
        self.actionAbout.setText(_translate("MMSMagPy", "About", None))
        self.actionPrint.setText(_translate("MMSMagPy", "Print", None))
        self.actionQuit.setText(_translate("MMSMagPy", "Quit", None))
        self.actionBy_Day.setText(_translate("MMSMagPy", "By Day", None))
        self.actionManually.setText(_translate("MMSMagPy", "Manually", None))
        self.actionFilename.setText(_translate("MMSMagPy", "Filename Format", None))
        self.actionWorking_Directory.setText(_translate("MMSMagPy", "Working Directory", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MMSMagPy = QtGui.QMainWindow()
    ui = Ui_MMSMagPy()
    ui.setupUi(MMSMagPy)
    MMSMagPy.show()
    sys.exit(app.exec_())

